import Head from 'next/head';
import Link from 'next/link';
import Footer from '../components/Footer';

const EFFECTIVE_DATE = 'June 1, 2025';
const CONTACT_EMAIL  = 'hello@sayhelloleads.com';

export default function TermsPage() {
  return (
    <>
      <Head>
        <title>Terms of Service — Say HelloLeads</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,500;9..40,600&display=swap" rel="stylesheet" />
      </Head>

      <style jsx global>{`
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { background: #fafaf8; color: #0a0a0a; font-family: 'DM Sans', sans-serif; min-height: 100vh; display: flex; flex-direction: column; }
        a { color: #4a6741; }
        a:hover { text-decoration: underline; }
        ul { padding-left: 1.25rem; display: flex; flex-direction: column; gap: .35rem; }
        li { font-size: 14px; color: #3a3a3a; line-height: 1.75; }
      `}</style>

      <nav style={{ borderBottom: '1px solid #e0ddd8', padding: '.9rem 2rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: '#fafaf8' }}>
        <Link href="/" style={{ fontSize: '17px', fontWeight: '700', color: '#0a0a0a', textDecoration: 'none', letterSpacing: '-.3px' }}>
          Say <span style={{ color: '#4a6741' }}>HelloLeads</span>
        </Link>
        <Link href="/" style={{ fontSize: '13px', color: '#6b6b6b', textDecoration: 'none' }}>← Back to home</Link>
      </nav>

      <main style={{ flex: 1, maxWidth: '720px', margin: '0 auto', padding: '3rem 2rem' }}>

        <div style={{ marginBottom: '2.5rem' }}>
          <h1 style={{ fontSize: '28px', fontWeight: '700', letterSpacing: '-.4px', marginBottom: '.5rem' }}>Terms of Service</h1>
          <p style={{ fontSize: '13px', color: '#6b6b6b' }}>Effective date: {EFFECTIVE_DATE}</p>
        </div>

        <Section title="1. Acceptance of terms">
          By creating an account or using Say HelloLeads, you agree to these Terms of Service. If you do not agree, do not use the platform.
        </Section>

        <Section title="2. Description of service">
          Say HelloLeads provides an AI-powered lead response platform for real estate agents. We automate first responses to buyer inquiries, qualify leads through conversation, and present scored results in a dashboard.
        </Section>

        <Section title="3. Your account">
          <ul>
            <li>You are responsible for maintaining the confidentiality of your login credentials.</li>
            <li>You must provide accurate information when registering.</li>
            <li>You may not share your account or use it to represent multiple agents without written permission.</li>
            <li>You must be at least 18 years old to use this service.</li>
          </ul>
        </Section>

        <Section title="4. Acceptable use">
          You agree not to:
          <ul>
            <li>Use the platform for any unlawful purpose or in violation of applicable real estate regulations.</li>
            <li>Misrepresent yourself, your agency, or your services to leads.</li>
            <li>Attempt to reverse engineer, copy, or resell any part of the platform.</li>
            <li>Use the platform to send spam or unsolicited communications.</li>
          </ul>
        </Section>

        <Section title="5. AI-generated content">
          The AI responses generated by Say HelloLeads are automated and may not always be perfectly accurate. You are responsible for reviewing lead conversations and following up appropriately. We are not liable for any inaccuracies in AI-generated messages sent on your behalf.
        </Section>

        <Section title="6. Data and privacy">
          Your use of the platform is also governed by our <Link href="/privacy">Privacy Policy</Link>, which is incorporated into these terms by reference.
        </Section>

        <Section title="7. Service availability">
          We aim for high availability but do not guarantee uninterrupted access. We may perform maintenance, upgrades, or experience outages. We are not liable for losses resulting from downtime.
        </Section>

        <Section title="8. Limitation of liability">
          To the maximum extent permitted by law, Say HelloLeads shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the platform, including lost leads, lost revenue, or missed opportunities.
        </Section>

        <Section title="9. Termination">
          We reserve the right to suspend or terminate your account at any time for violations of these terms or for any other reason with reasonable notice. You may delete your account at any time from within the app.
        </Section>

        <Section title="10. Changes to terms">
          We may update these terms from time to time. Material changes will be communicated by email. Continued use after changes constitutes acceptance.
        </Section>

        <Section title="11. Contact" last>
          Questions about these terms? Reach us at{' '}
          <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
        </Section>

      </main>

      <Footer />
    </>
  );
}

function Section({ title, children, last }) {
  return (
    <section style={{ marginBottom: last ? 0 : '2.25rem' }}>
      <h2 style={{ fontSize: '15px', fontWeight: '700', color: '#0a0a0a', marginBottom: '.75rem', paddingBottom: '.5rem', borderBottom: '1px solid #e0ddd8' }}>
        {title}
      </h2>
      <div style={{ fontSize: '14px', color: '#3a3a3a', lineHeight: '1.75', display: 'flex', flexDirection: 'column', gap: '.6rem' }}>
        {children}
      </div>
    </section>
  );
}
